name: deploy

on:
    push:
    workflow_dispatch:
    schedule:
        # Runs everyday at 8:00 AM
        - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"

            - name: Build Web
              run: hugo

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}  # 注意填写main或者master
              with:
                  personal_token: ${{ secrets.BLOG}} # 如果secret取了其他名称，将MY_PAT替换掉
                  external_repository: 9isli/9isli.github.io # 填写远程仓库，不一定是这个格式，按照自己的情况写 
                  publish_dir: ./public
                  cname: blog.nuclear-pomelo.top        # 填写你的自定义域名。如果没有用自定义域名，注释掉这行
